/**
 * @file one_point.cpp 
 * @author Christian Laguerre <christian.laguerre@math.cnrs.fr> (2012-2017)
 * @version 1.07.01
 * @date 2017-02-16
 *
 * @brief One point %output
 * @details 
 * %Output format:
 * optimized for %Gnuplot .
 *
 * @copyright License Cecill-V2 \n
 * <http://www.cecill.info/licences/Licence_CeCILL_V2-en.html>
 *
 * (c) CNRS - Universite d'Orleans - BRGM (France)
 */
/* 
 *
 * This file is part of FullSWOF_2D software. 
 * <https://sourcesup.renater.fr/projects/fullswof-2d/> 
 *
 * FullSWOF_2D = Full Shallow-Water equations for Overland Flow, 
 * in two dimensions of space.
 * This software is a computer program whose purpose is to compute
 * solutions for 2D Shallow-Water equations.
 *
 * LICENSE
 *
 * This software is governed by the CeCILL license under French law and
 * abiding by the rules of distribution of free software. You can use,
 * modify and/ or redistribute the software under the terms of the CeCILL
 * license as circulated by CEA, CNRS and INRIA at the following URL
 * <http://www.cecill.info>.
 *
 * As a counterpart to the access to the source code and rights to copy,
 * modify and redistribute granted by the license, users are provided only
 * with a limited warranty and the software's author, the holder of the
 * economic rights, and the successive licensors have only limited
 * liability.
 *
 * In this respect, the user's attention is drawn to the risks associated
 * with loading, using, modifying and/or developing or reproducing the
 * software by the user in light of its specific status of free software,
 * that may mean that it is complicated to manipulate, and that also
 * therefore means that it is reserved for developers and experienced
 * professionals having in-depth computer knowledge. Users are therefore
 * encouraged to load and test the software's suitability as regards their
 * requirements in conditions enabling the security of their systems and/or
 * data to be ensured and, more generally, to use and operate it in the
 * same conditions as regards security.
 *
 * The fact that you are presently reading this means that you have had
 * knowledge of the CeCILL license and that you accept its terms.
 *
 ******************************************************************************/


#include "one_point.hpp"

One_point::One_point(Parameters & par):Save_specific_points(par){
  
  /**
   * @details  
   * Writes the header of the file 'hu_specific_points.dat'.
   * @param[in] par parameter, contains all the values from the parameters file.
   * @warning ***: ERROR: Impossible to open the *** file. Verify if the directory *** exists.
   * @note If hu_specific_points.dat cannot be opened, the code will exit with failure termination code.
   */

  x_coord = par.get_x_coord();
  y_coord = par.get_y_coord();
  
  outputDirectory = par.get_outputDirectory();
  namefile = outputDirectory + "hu_specific_points.dat";
  
  ofstream outsave(namefile.c_str(),ios::out);
  if (!outsave){
    cerr << "Impossible to open the " << namefile.c_str() <<" file\n";
    cerr << "Verify if the directory " << outputDirectory <<" exists\n";
    exit(EXIT_FAILURE);
  }
  outsave << "################################################################################ "<< endl;
  outsave << "# Generated by "<< VERSION << endl; 
  outsave << "################################################################################ "<< endl;
  outsave << "# time " << "\t" << "(i-0.5)*dx " << "\t"<< setw(9) << "(j-0.5)*dy" << "\t"<< setw(9) << " h[i][j] " << "\t"<< setw(9) << " u[i][j] " << "\t"<< setw(9) << "v[i][j]"  << endl;
  outsave << "# " << endl;
  outsave.close();
  
}

void One_point::save(const TAB & h, const TAB & u, const TAB & v, const SCALAR time){
  
  /**
   * @details
   * Writes the values of Scheme#h, Scheme#u (=q1/h), Scheme#v (=q2/h), Scheme#h+ Scheme#z (free surface),
   * Scheme#z, \f$ |U| = \sqrt{u^2+v^2}\f$, the Froude number \f$ \frac{|U|}{\sqrt{gh}}\f$, Scheme#q1, Scheme#q2,
   * and \f$ h|U|\f$ at the current time in "hu_specific_points.dat". \n
   * If the water height is too small, we replace it by 0, the velocity is null and the Froude number does not exist.
   * @param[in] h the water height.
   * @param[in] u first component of the velocity.
   * @param[in] v second component of the velocity.
   * @param[in] time the current time.
   */


  if (time >= T_output){ // If the user does not want to save each time step,
                         // We save the first time after the time step written in parameters.txt file

    ofstream outsave(namefile.c_str(),ios::app);
    
#ifdef DEBUG
    outsave.precision(10);
#endif
    
    //We compute the index of the array from the space variable in the input file.
    row=(int)ceil(x_coord/DX); column=(int)ceil(y_coord/DY); //The index corresponds to the smallest integer superior or equal to x/dx or y/dy.

  if (h[row][column]<HE_CA){
      outsave << time <<  "\t" << x_coord << "\t" << setw(9) << y_coord << "\t" << setw(9) << "0.0" << "\t" << setw(9) << "0.0" << "\t" << setw(9) << "0.0"  << endl;
    }
    else{
      outsave << time <<  "\t" << x_coord << "\t" << setw(9) << y_coord << "\t" << setw(9) << h[row][column] << "\t" << setw(9) << u[row][column] << "\t" << setw(9) << v[row][column]  << endl;
    }
    
    outsave.close();

    T_output+=DT_SPECIFIC_POINTS;
  }    
}


One_point::~One_point(){
}


